# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-12 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile_details',
        ),
    ]
